module Type where

newtype AbbreviationNumber = Abbreviation Int deriving (Show)
newtype AbbrevTableBase = AbbreviationTableBase Int deriving (Show)
newtype BitNumber = BitNumber Int deriving (Show)
newtype BitSize = BitSize Int deriving (Show)
newtype ByteAddress = ByteAddress Int deriving (Show)
newtype DictionaryBase = DictionaryBase Int deriving (Show)
newtype DictionaryTableBase = DictionaryTableBase Int deriving (Show)
newtype DictionaryAddress = DictionaryAddress Int deriving (Show)
newtype DictionaryNumber = Dictionary Int deriving (Show)
newtype WordAddress = WordAddress Int deriving (Show)
newtype WordZstringAddress = WordZstring Int deriving (Show)
newtype Zchar = Zchar Int deriving (Show)
newtype ZstringAddress = Zstring Int deriving (Show)